### Demographics

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')
%matplotlib inline 
sns.set_style(style='whitegrid')
sns.set_theme(rc={'figure.figsize':(11.7,8.27)})
pd.options.display.max_rows = 4000

In [2]:
w1_raw = pd.read_csv('../data/raw/w1_demographics.csv')

In [3]:
w1_raw.head()

,household_ID,member_ID,age,relationship_to_the_head_of_household,gender,ethnicity,religion,marital_status,current_attendance_in_any_education_instituition,highest_level_of_education,main_activity_engaged_in,main_occupation,daily_wage_owner_or_not,employment_status_of_the_main_occupation,no_of_hours_stayed_at_home_during_last_week,member_went_out_for_work_or_not_during_last_week
0,ID0001,I1,71,Head of the household,Male,Sinhala,Buddhism,Currently married (registered),Does not attend,Passed G.C.E.(A/L) or equivalent,Retired and obtaining government/semi-governme...,Related to forces,No,Government employee,168.0,"No, worked from home"
1,ID0001,I2,66,Wife/Husband,Female,Sinhala,Buddhism,Currently married (registered),Does not attend,Passed G.C.E.(A/L) or equivalent,Household activities,NaN,NaN,NaN,168.0,NaN
2,ID0001,I3,32,Son/daughter,Male,Sinhala,Buddhism,Currently married (registered),Does not attend,Passed post Graduate Degree / Diploma,Engaged in economic activity/ currently employ...,Professional,No,Government employee,70.0,"Yes, went daily during working days"
3,ID0001,I4,30,Son-in-law/Daughter in law,Female,Sinhala,Buddhism,Currently married (registered),Does not attend,Passed post Graduate Degree / Diploma,Engaged in economic activity/ currently employ...,Professional,No,Government employee,150.0,"Yes, went daily during working days"
4,ID0002,I1,85,Head of the household,Male,Sinhala,Buddhism,Currently married (registered),Does not attend,Passed Grade 6,Retired - Obtaining government/semi-government...,NaN,NaN,NaN,168.0,NaN

In [4]:
w1_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16270 entries, 0 to 16269
Data columns (total 16 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   household_ID                                      16270 non-null  object
 1   member_ID                                         16270 non-null  object
 2   age                                               16270 non-null  int64
 3   relationship_to_the_head_of_household             16270 non-null  object
 4   gender                                            16270 non-null  object
 5   ethnicity                                         16270 non-null  object
 6   religion                                          16270 non-null  object
 7   marital_status                                    16270 non-null  object
 8   current_attendance_in_any_education_instituition  15852 non-null  object
 9   highest_level_of_education                        15495 non-null  object
 10  main_activity_engaged_in                          14137 non-null  object
 11  main_occupation                                   6368 non-null   object
 12  daily_wage_owner_or_not                           6180 non-null   object
 13  employment_status_of_the_main_occupation          6368 non-null   object
 14  no_of_hours_stayed_at_home_during_last_week       16270 non-null  float64
 15  member_went_out_for_work_or_not_during_last_week  4303 non-null   object
dtypes: float64(1), int64(1), object(14)
memory usage: 2.0+ MB

In [5]:
cols = [
    'household_ID',
    'member_ID',
    'age',
    'gender',
    'main_activity_engaged_in',
    'no_of_hours_stayed_at_home_during_last_week'
]

In [6]:
w1 = pd.read_csv('../data/raw/w1_demographics.csv')[cols]

w2_new = pd.read_csv('../data/raw/w2_new_household_members.csv')[cols]

w3_new = pd.read_csv('../data/raw/w3_new_household_members.csv')[cols]

In [7]:
survey_dates = pd.read_csv('../data/raw/survey_dates.csv')

In [8]:
survey_dates['wave1'] = pd.to_datetime(survey_dates['wave1'], errors='coerce')
survey_dates['wave2'] = pd.to_datetime(survey_dates['wave2'], errors='coerce')
survey_dates['wave3'] = pd.to_datetime(survey_dates['wave3'], errors='coerce')

In [9]:
w1['wave'] = 1
w2_new['wave'] = 2
w3_new['wave'] = 3

In [10]:
wave1_ids = survey_dates[~survey_dates['wave1'].isna()]['household_ID']
wave2_ids = survey_dates[~survey_dates['wave2'].isna()]['household_ID']
wave3_ids = survey_dates[~survey_dates['wave3'].isna()]['household_ID']

In [11]:
wave1_full = w1.copy()

wave1_full = wave1_full.merge(
    survey_dates[['household_ID', 'wave1']],
    on='household_ID',
    how='left'
)

wave1_full['survey_date'] = wave1_full['wave1']
wave1_full['wave'] = 1
wave1_full = wave1_full.drop(columns=['wave1'])

In [12]:
wave2_full = pd.concat([w1, w2_new], ignore_index=True)

wave2_full = wave2_full.merge(
    survey_dates[['household_ID', 'wave2']],
    on='household_ID',
    how='left'
)

wave2_full['survey_date'] = wave2_full['wave2']
wave2_full['wave'] = 2

wave2_full = wave2_full.drop(columns=['wave2'])

In [13]:
wave3_full = pd.concat([w1, w2_new, w3_new], ignore_index=True)

wave3_full = wave3_full.merge(
    survey_dates[['household_ID', 'wave3']],
    on='household_ID',
    how='left'
)

wave3_full['survey_date'] = wave3_full['wave3']
wave3_full['wave'] = 3

wave3_full = wave3_full.drop(columns=['wave3'])

In [14]:
all_df = pd.concat([
    wave1_full,
    wave2_full,
    wave3_full
], ignore_index=True)

In [15]:
all_df.groupby(['household_ID', 'survey_date'])['member_ID'].nunique()

household_ID  survey_date
ID0001        2023-12-09     4
              2024-09-30     5
              2024-11-28     5
ID0002        2023-12-09     3
              2024-10-02     3
                            ..
ID4062        2024-11-11     2
              2024-12-17     2
ID4063        2024-10-24     5
              2024-11-10     5
              2024-12-23     5
Name: member_ID, Length: 10974, dtype: int64

In [16]:
all_df.isna().sum()

household_ID                                      0
member_ID                                         0
age                                               0
gender                                            0
main_activity_engaged_in                       6739
no_of_hours_stayed_at_home_during_last_week       0
wave                                              0
survey_date                                    4810
dtype: int64

In [17]:
all_df.head()

,household_ID,member_ID,age,gender,main_activity_engaged_in,no_of_hours_stayed_at_home_during_last_week,wave,survey_date
0,ID0001,I1,71,Male,Retired and obtaining government/semi-governme...,168.0,1,2023-12-09
1,ID0001,I2,66,Female,Household activities,168.0,1,2023-12-09
2,ID0001,I3,32,Male,Engaged in economic activity/ currently employ...,70.0,1,2023-12-09
3,ID0001,I4,30,Female,Engaged in economic activity/ currently employ...,150.0,1,2023-12-09
4,ID0002,I1,85,Male,Retired - Obtaining government/semi-government...,168.0,1,2023-12-09

In [18]:
check = all_df.groupby(['household_ID', 'survey_date'])['member_ID'].nunique().reset_index()

In [19]:
check = check.sort_values(['household_ID', 'survey_date'])

In [20]:
check.head(15)

   household_ID survey_date  member_ID
0        ID0001  2023-12-09          4
1        ID0001  2024-09-30          5
2        ID0001  2024-11-28          5
3        ID0002  2023-12-09          3
4        ID0002  2024-10-02          3
5        ID0002  2024-12-11          3
6        ID0003  2023-12-09          4
7        ID0003  2024-10-06          4
8        ID0003  2025-01-12          4
9        ID0004  2023-12-09          4
10       ID0005  2023-12-09          2
11       ID0005  2024-10-15          2
12       ID0005  2024-12-05          2
13       ID0006  2023-12-09          6
14       ID0006  2024-10-14          6

In [21]:
all_df = all_df.drop_duplicates(
    subset=['household_ID', 'survey_date', 'member_ID']
)

In [22]:
all_df['main_activity_engaged_in'].value_counts().to_frame()

                                                    count
main_activity_engaged_in
Engaged in economic activity/ currently employe...  15667
Household activities                                 9970
Student                                              7193
Too old / Disable/ unable to work                    2472
Retired and obtaining government/semi-governmen...   2016
Retired - Obtaining government/semi-government ...   1047
Retired from the private/semi-government sector...    763
Seeking for and available to work                     633
1.Engaged in economic activity/ currently emplo...    573
Received other pension payments                       443
Other                                                 330
7.Household activities                                308
8.Student                                             200
9.Too old / Disable/ unable to work.                  106
2.Retired and obtaining government/semi-governm...     54
3.Seeking for and available to work                    25
4.Retired - Obtaining government/semi-governmen...     13
6.Received other pension payments.                     11
5.Retired from the private/semi-government sect...     11
10.Other                                                7

In [23]:
activity_map = {
    'Engaged in economic activity/ currently employed/ engaged in own business': 'employed',    
    'Household activities': 'not_employed',
    'Student': 'not_employed',
    'Too old / Disable/ unable to work': 'not_employed',
    'Retired and obtaining government/semi-government pension payment and is currently engaged in economic activity (employed elsewhere other than the place where he/she is receiving the pension from / engaged in own business)': 'employed',
    '1.Engaged in economic activity/ currently employed/ engaged in own business': 'employed',
    'Retired - Obtaining government/semi-government pension payment and currently not engaged in economic activity (not employed elsewhere or not engaged in any own business)': 'not_employed',
    'Retired from the private/semi-government sector and does not obtain any pension payment': 'not_employed',
    '7.Household activities': 'not_employed',
    'Seeking for and available to work': 'not_employed',
    'Received other pension payments': 'not_employed',
    '8.Student': 'not_employed',
    'Other': 'not_employed',
    '9.Too old / Disable/ unable to work.': 'not_employed',
    '2.Retired and obtaining government/semi-government pension payment and is currently engaged in economic activity (employ': 'employed',
    '3.Seeking for and available to work': 'not_employed',
    '6.Received other pension payments.': 'not_employed',
    '4.Retired - Obtaining government/semi-government pension payment and currently not engaged in economic activity (not emp': 'not_employed',
    '5.Retired from the private/semi-government sector and does not obtain any pension payment.': 'not_employed',
    '10.Other': 'not_employed'
}

In [24]:
all_df['activity'] = all_df['main_activity_engaged_in'].map(activity_map)

In [25]:
all_df.head()

,household_ID,member_ID,age,gender,main_activity_engaged_in,no_of_hours_stayed_at_home_during_last_week,wave,survey_date,activity
0,ID0001,I1,71,Male,Retired and obtaining government/semi-governme...,168.0,1,2023-12-09,employed
1,ID0001,I2,66,Female,Household activities,168.0,1,2023-12-09,not_employed
2,ID0001,I3,32,Male,Engaged in economic activity/ currently employ...,70.0,1,2023-12-09,employed
3,ID0001,I4,30,Female,Engaged in economic activity/ currently employ...,150.0,1,2023-12-09,employed
4,ID0002,I1,85,Male,Retired - Obtaining government/semi-government...,168.0,1,2023-12-09,not_employed

In [26]:
all_df.isna().sum()

household_ID                                      0
member_ID                                         0
age                                               0
gender                                            0
main_activity_engaged_in                       6449
no_of_hours_stayed_at_home_during_last_week       0
wave                                              0
survey_date                                    2669
activity                                       6449
dtype: int64

In [27]:
all_df.shape

(48291, 9)

In [28]:
all_df['is_employed'] = (all_df['activity'] == 'employed').astype(int)

In [29]:
all_df.head(15)

,household_ID,member_ID,age,gender,main_activity_engaged_in,no_of_hours_stayed_at_home_during_last_week,wave,survey_date,activity,is_employed
0,ID0001,I1,71,Male,Retired and obtaining government/semi-governme...,168.0,1,2023-12-09,employed,1
1,ID0001,I2,66,Female,Household activities,168.0,1,2023-12-09,not_employed,0
2,ID0001,I3,32,Male,Engaged in economic activity/ currently employ...,70.0,1,2023-12-09,employed,1
3,ID0001,I4,30,Female,Engaged in economic activity/ currently employ...,150.0,1,2023-12-09,employed,1
4,ID0002,I1,85,Male,Retired - Obtaining government/semi-government...,168.0,1,2023-12-09,not_employed,0
5,ID0002,I2,66,Male,Retired and obtaining government/semi-governme...,0.0,1,2023-12-09,employed,1
6,ID0002,I3,59,Female,Retired and obtaining government/semi-governme...,168.0,1,2023-12-09,employed,1
7,ID0003,I1,44,Male,Retired and obtaining government/semi-governme...,100.0,1,2023-12-09,employed,1
8,ID0003,I2,41,Female,Retired and obtaining government/semi-governme...,100.0,1,2023-12-09,employed,1
9,ID0003,I3,74,Female,Retired - Obtaining government/semi-government...,168.0,1,2023-12-09,not_employed,0
10,ID0003,I4,11,Male,NaN,100.0,1,2023-12-09,NaN,0
11,ID0004,I1,35,Male,Engaged in economic activity/ currently employ...,70.0,1,2023-12-09,employed,1
12,ID0004,I2,71,Female,Household activities,70.0,1,2023-12-09,not_employed,0
13,ID0004,I3,32,Female,Household activities,168.0,1,2023-12-09,not_employed,0
14,ID0004,I4,4,Male,NaN,148.0,1,2023-12-09,NaN,0

In [30]:
all_df.isna().sum()

household_ID                                      0
member_ID                                         0
age                                               0
gender                                            0
main_activity_engaged_in                       6449
no_of_hours_stayed_at_home_during_last_week       0
wave                                              0
survey_date                                    2669
activity                                       6449
is_employed                                       0
dtype: int64

In [31]:
all_df['is_child'] = (all_df['age'] < 18).astype(int)
all_df['is_elderly'] = (all_df['age'] >= 60).astype(int)

In [32]:
household_df = all_df.groupby(['household_ID', 'survey_date']).agg({
    'member_ID': 'count',
    'age': ['mean', 'max'],
    'is_child': 'sum',
    'is_elderly': 'sum',
    'is_employed': 'sum',
    'no_of_hours_stayed_at_home_during_last_week': 'mean',
}).reset_index()

In [33]:
household_df.columns = [
    'household_ID',
    'survey_date',
    'household_size',
    'avg_age',
    'max_age',
    'num_children',
    'num_elderly',
    'num_employed',
    'avg_hours_home',
]

In [34]:
household_df['dependency_ratio'] = (
    (household_df['num_children'] + household_df['num_elderly']) /
    household_df['household_size']
)

In [35]:
household_df['employment_ratio'] = (
    household_df['num_employed'] / household_df['household_size']
)

In [36]:
household_df['num_adults'] = (
    household_df['household_size'] -
    household_df['num_children']
)

In [37]:
household_df.head(15)

,household_ID,survey_date,household_size,avg_age,max_age,num_children,num_elderly,num_employed,avg_hours_home,dependency_ratio,employment_ratio,num_adults
0,ID0001,2023-12-09,4,49.750000,71,0,2,3,139.000000,0.500000,0.750000,4
1,ID0001,2024-09-30,5,40.200000,71,1,2,3,132.800000,0.600000,0.600000,4
2,ID0001,2024-11-28,5,40.200000,71,1,2,3,132.800000,0.600000,0.600000,4
3,ID0002,2023-12-09,3,70.000000,85,0,2,2,112.000000,0.666667,0.666667,3
4,ID0002,2024-10-02,3,70.000000,85,0,2,2,112.000000,0.666667,0.666667,3
5,ID0002,2024-12-11,3,70.000000,85,0,2,2,112.000000,0.666667,0.666667,3
6,ID0003,2023-12-09,4,42.500000,74,1,1,2,117.000000,0.500000,0.500000,3
7,ID0003,2024-10-06,4,42.500000,74,1,1,2,117.000000,0.500000,0.500000,3
8,ID0003,2025-01-12,4,42.500000,74,1,1,2,117.000000,0.500000,0.500000,3
9,ID0004,2023-12-09,4,35.500000,71,1,1,1,114.000000,0.500000,0.250000,3
10,ID0005,2023-12-09,2,67.500000,78,0,1,1,126.000000,0.500000,0.500000,2
11,ID0005,2024-10-15,2,67.500000,78,0,1,1,126.000000,0.500000,0.500000,2
12,ID0005,2024-12-05,2,67.500000,78,0,1,1,126.000000,0.500000,0.500000,2
13,ID0006,2023-12-09,6,26.333333,48,3,0,2,103.916667,0.500000,0.333333,3
14,ID0006,2024-10-14,6,26.333333,48,3,0,2,103.916667,0.500000,0.333333,3

In [38]:
household_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10974 entries, 0 to 10973
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   household_ID      10974 non-null  object
 1   survey_date       10974 non-null  datetime64[ns]
 2   household_size    10974 non-null  int64
 3   avg_age           10974 non-null  float64
 4   max_age           10974 non-null  int64
 5   num_children      10974 non-null  int64
 6   num_elderly       10974 non-null  int64
 7   num_employed      10974 non-null  int64
 8   avg_hours_home    10974 non-null  float64
 9   dependency_ratio  10974 non-null  float64
 10  employment_ratio  10974 non-null  float64
 11  num_adults        10974 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(6), object(1)
memory usage: 1.0+ MB

In [39]:
household_df_reorder = household_df[['household_ID', 'survey_date', 'household_size', 'avg_age', 'max_age', 'num_children', 'num_adults', 'num_elderly', 'num_employed', 'avg_hours_home', 'dependency_ratio', 'employment_ratio']]

In [40]:
household_df_reorder.head()

,household_ID,survey_date,household_size,avg_age,max_age,num_children,num_adults,num_elderly,num_employed,avg_hours_home,dependency_ratio,employment_ratio
0,ID0001,2023-12-09,4,49.75,71,0,4,2,3,139.0,0.500000,0.750000
1,ID0001,2024-09-30,5,40.20,71,1,4,2,3,132.8,0.600000,0.600000
2,ID0001,2024-11-28,5,40.20,71,1,4,2,3,132.8,0.600000,0.600000
3,ID0002,2023-12-09,3,70.00,85,0,3,2,2,112.0,0.666667,0.666667
4,ID0002,2024-10-02,3,70.00,85,0,3,2,2,112.0,0.666667,0.666667

In [41]:
household_df_reorder.to_csv("../data/processed/household_demographics.csv", index=False)